### ISSUE TITLE
Common SCSS not working

### ISSUE THREAD

**Issue by sjumble** [asadsahi/AspNetCoreSpa#122]
Added a new _main.scss in Style folder.
Then imported in Main.ts, also tested the same by importing in app.component.ts
The css in _main.scss are not been applied, can some please added a new _main.scss and let us know how to import a new global scss file.

**Comment by m2017atTR** [comment]
Can be fixed by various ways,
- mine is add  encapsulation: ViewEncapsulation.None to app.component.ts then add global css 


        @Component({

         selector: 'appc-root',
        templateUrl: './app.component.html',
        styleUrls: [
         './app.component.scss'
         ,'./primengtheme.scss'
         ,'./primengbase.scss'
          ],
        encapsulation: ViewEncapsulation.None
       })
      export class AppComponent implements OnInit {



- other way can be manage by angular cli
in .angular-cli.json
add to
 "styles": [ '....css','....'],
      "scripts": [  ]

- another way add to webpack and put css file links to index file.

**Comment by asadsahi** [comment]
@sjumble try @m2017atTR 's idea, if there is any particular issue you still encounter please share a repo with reproduction. Thanks
