### ISSUE TITLE
Facebook question

### ISSUE THREAD

**Issue by floriandubois** [asadsahi/AspNetCoreSpa#131]
Hi,

What should be the Valid OAuth redirect URIs during debug (let's say I'm on http://localhost:5000)?
I tried multiple urls but can't figure out what it should be.

Thank you for your help.

**Comment by floriandubois** [comment]
So I figured out I just need to pass http://localhost:5000 as url. Now, the thing is after authenticating with facebook the url becomes /Account/AccessDenied?ReturnUrl=... 
What does it mean? Is it because the user is not registered in the local db?

**Comment by asadsahi** [comment]
@floriandubois since this is a single page application I have implemented token based authentication for social logins after user has confirmed from their social providers. Master branch has these changes in it. Please also see [this](https://github.com/asadsahi/AspNetCoreSpa/issues/62) issue and [this ](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup)wiki.
