### ISSUE TITLE
Angular Material 2 - Branch Is that possible

### ISSUE THREAD

**Issue by kanpinar** [asadsahi/AspNetCoreSpa#134]
Hello I think another branch is needed, for using with Angular Material ...

Is that possible ? #44 #102

**Comment by ehouarn-perret** [comment]
@kanpinar 
Related stuff: https://github.com/aspnet/JavaScriptServices/issues/1231
I managed to make it work, I started to work on a solution... if it can help, I plan to create template once I'm done. The template would be something like the bootstrap one except using the datatable instead of the table for the weather forecasts example, the sidenav instead of the bootstrap nav.

My repository: https://github.com/ehouarn-perret/EhouarnPerret.CSharp.AngularMaterial2

I got hard times to make it work (documentation is sparsed especially when it comes to the development mode). The only things that remain to be done:  
 * Complete to convert the bootstrap example with angular material 2 maybe with more controls or examples (I have a couple of things on my mind...) anyway should not be that hard
 * Solve the issue about webpack regeneration, I have a rendering duplication issue:

**Comment by ehouarn-perret** [comment]
Related stuff: 
 * https://github.com/aspnet/JavaScriptServices/issues/1231

**Comment by asadsahi** [comment]
@kanpinar I don't have any plan to create material branch right now. However implementation should be straight forward just like any other UI framework/library. Maybe once material 2 is finally released I can give it a go to avoid handling breaking changes until then.
