### ISSUE TITLE
have different layout for different modules

### ISSUE THREAD

**Issue by h4m3d66** [asadsahi/AspNetCoreSpa#157]
How can I have different layout for different modules?

**Comment by asadsahi** [comment]
@h4m3d66 can you explain a little more about what layout are you taking about for different modules?

**Comment by h4m3d66** [comment]
I have separate module for each section of my web application, for example one module for user account, one module for shopping,... I want each module have its own layout. How I can do that?

**Comment by asadsahi** [comment]
@h4m3d66 If you are looking to achieve different layouts such as different navigations etc I would suggest looking into https://docs.google.com/presentation/d/1o1zbqxe-Fn4IdGRYeVGFNQb1PSiOpjXvIsNHRC7Bk1w/edit. this explains one way to achieve this. Since each module has different navigations, you could achieve something similar by providing different components based on the route you are on.

**Comment by crh225** [comment]
from @asadsahi  link,
we did something similar to 
![image](https://user-images.githubusercontent.com/19475195/32840252-be40e2ca-c9dc-11e7-9118-3b6ce05a3006.png)

Each route that gets loaded into the router outlet is a different module for us. We actually are taking each module and putting it into its own scoped (private) npm package for our different areas of our business. (Accouting, Logistics, ...) These modules for us are in a since, their own applications.

**Comment by h4m3d66** [comment]
I want some module have completely different layout(master page) not just its main content, for example in some module I dont want left nav and I want right nav or I dont want have left nav or right nav at all.

**Comment by asadsahi** [comment]
@h4m3d66 link I sent of slides have demo links at the bottom as well. Have you looked at it?

What you are trying to achieve sounds similar to what Alex from angular core team mentioned in his presentation, that you can build dynamic views for different routes.

**Comment by asadsahi** [comment]
closing as this is outside scope of this project.
