### ISSUE TITLE
Project with mdbootstrap.com

### ISSUE THREAD

**Issue by Shelliniho** [asadsahi/AspNetCoreSpa#159]
Hello, I've been trying to integrate the mdbootstrap for angular into the project for a few days. Unfortunately unsuccessful. Is that possible somehow?

**Comment by asadsahi** [comment]
@Shelliniho I haven't used mdbootstrap myself, but can't see any problem using it with this project as mdbootstrap requires only css and javascript. Can you explain or share a repo which demonstrates specific problem and i can help you figuring out the issue.

**Comment by Shelliniho** [comment]
The Angular version runs with SCSS. Here is the tutorial https://mdbootstrap.com/angular/5min-quickstart/
If I install all this and then create the project, I get the message, at-loader error with @ sign in the SCSS and TS files.

**Comment by kmiskiewicz** [comment]
I have a proposition, if it doesn't make sense I'm sorry but one of the biggest advantages of newer versions of angular is SSR which can be impossible to achieve with mdbootrap https://mdbootstrap.com/support/mdbootstrap-angular-universal-server-side-rendering-errors/   Maybe instead of fighting with problems which we cannot solve on our end we should just switch to  https://github.com/angular/material2 ?  I don't have a lot of experience we the newest frameworks because the last few years I spent mainly with AngularJS

**Comment by kostia24** [comment]
mdbootstrap npm package contains only ts and scss files. So to use it you first need to compile. The fastest way for me was to include mdbootstrap ts in main bundle.

**Comment by asadsahi** [comment]
Closing this for as it isn't directly related to this project. If someone has a specific problem integrating 3rd party libraries, then please share a repo with very particular issue and I can try and have a look.

Hope thats OK.
