### ISSUE TITLE
Bootstrap 4 js support

### ISSUE THREAD

**Issue by layinka** [asadsahi/AspNetCoreSpa#171]
Hi,
Pls how do i add the full bootstrap 4 js to the app?

It seems that jquery and popper are not loading now, and i have tried different ways of adding them to the webpack.vendor file, but its still not working.

And things like dropdown etc are not working without the js

**Comment by asadsahi** [comment]
@layinka I personally don't have experience working both jquery and ng-bootstrap working together as they are mutually exclusive I guess. 

ng-bootstrap is alternative to jquery based implementation of bootstrap components so I would suggest if you can use ng-boostrap instead of relying on jquery (I think popover component is also included in ng-boostrap components).

In terms of making it working, just a random guess since I haven't tried myself, but try removing ng-boostrap from project and then add bootstrap js.

**Comment by layinka** [comment]
Ok thanks, 
I will keep using ng-bootstrap then
