### ISSUE TITLE
can you create same project use react redux?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#177]
Dear Asad Sahi.
Can you create same project use react redux? or you guide me what link github project react + netcore2

Many thank.

**Comment by kmiskiewicz** [comment]
@meninjanho4788  I'd like to share with you what I found about NGRX. It's difficult to find a good demo project which contains it...what I found people are divided between those who keep all actions/reducers in a one place and those who tries to decouple it. Here is really interesting project...which is a bit against what authors of NGRX published in their demo app https://github.com/orizens/ngrx-styleguide You don't need demo of ngrx and .net core because redux is only on client side.

**Comment by asadsahi** [comment]
@meninjanho4788 creating project using totally different client framework requires alot of learning curve and effort, especially with all the features which are included in this project. I hope you'll be able to find plenty of examples online where people have created react apps with different backends. If you like any existing backend functionality, you can easily used from this project and use it with react front-end. asp.net core spa templates have react starters as well, so that can be a good starting point as well. 

Unfortunately cannot suggest anything else since React + redux isn't my expertise at the moment. :)

**Comment by asadsahi** [comment]
@meninjanho4788 I am playing around with react and have created a fullstack project [here](https://github.com/asadsahi/reactnode-fullstack). That includes pretty much same features as this project. That project is using node as a backed rather .net. But see if you are interested in any of the similar concepts in react+redux.

**Comment by meninjanho4788** [comment]
Dear Asad Sahi, i really really thank you.
