### ISSUE TITLE
Simplification of two webpack files

### ISSUE THREAD

**Issue by AlejandroFlorin** [asadsahi/AspNetCoreSpa#178]
I may be wrong since I'm fairly new to webpack but as I understand it, the sharedConfig definitions in webpack.config.js and webpack.config.vendor.js  are useful for the visual studio angular template since it is  designed for server side rendering. Since AspNetCoreSpa doesn't support server side rendering (and therefore has no serverBundleConfig defined in either file ), does it make sense to have separate sharedConfig and clientBundleConfig combined with a merge command?

It wouldn't change any of the bundling of course but it would simplify things if the constants were dropped and a single configuration section was used. This could be done to both webpack.config.js and webpack.config.vendor.js.

**Comment by asadsahi** [comment]
@AlejandroFlorin thanks for pointing it out.

SSR is work in progress in angularcli/ssr branches which will become master once things are stabilised. After that there will not be any webpack configs since that is based on angular-cli.

Current master branch (which you are referring for these files will become a separate branch). Happy if someone can clean up some config and raise a PR. Sorry just time issues these days. :)
