### ISSUE TITLE
Cookie or Authorization barrer token in  auth-interceptor.ts 

### ISSUE THREAD

**Issue by kmiskiewicz** [asadsahi/AspNetCoreSpa#211]
Hi Asad,

I hope you are well, I was going trough the code and in the  auth-interceptor.ts I found something which I have problem to figure out. Why we have if statement on two not related things: culture and bearer token?

`    if (isPlatformServer(this.platformId)) {
            headers = req.headers.set('Cookie', this.getCultureCookie());
        } else {
            headers = req.headers.set('Authorization', 'Bearer ' + auth.accessToken);
        }`

Here is a link to the line:
https://github.com/asadsahi/AspNetCoreSpa/blob/64faeca0dab613ddd6307ab3ce0651575a717e02/ClientApp/src/app/core/services/interceptors/auth-interceptor.ts#L21

Best regards,
Krzysztof

**Comment by asadsahi** [comment]
@kmiskiewicz this logic says that only send cookies if environment is server, and only attach Authorization header if it is browser environment.

This code was added in order to prepare project for SSR, but in current master SSR isn't implemented fully because of some issues with it. I have simplified this logic, see [this](https://github.com/asadsahi/AspNetCoreSpa/commit/64975c58f7dd4c349de3facf5e5a8ef492648e09) change.

I am planning to make SSR working and alot more improvements in [dev](https://github.com/asadsahi/AspNetCoreSpa/tree/dev) branch which will be merged into master after .net 2.1 release and hopefully angular 6 by that time as well.  You can still try out dev branch as there are alot of improvements and the same cookie logic which was in authe.interceptor has been moved into a seperate interceptor. Alos, worth mentioning, .net build and runtime performance has massively improved. So, keep an eye :)

**Comment by kmiskiewicz** [comment]
Thank you, I didn't check the new dev version my bad, I'll observe the dev branch as well, really great job!
