### ISSUE TITLE
typing.d.ts

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#223]
@asadsahi  can you help me, please 

i want to import model reference in this file but this gives me error I need to implicitly add a typing.d.ts reference in each file.
because i need load application data on initial page load.
import { Category, IPostModel, City } from './app/shared/models/post.model';
/* SystemJS module definition */
declare var module: NodeModule;
declare var global: NodeJS.Global;
declare module NodeJS {
    interface Global {
        appData: IApplicationConfig
    }
}
interface NodeModule {
    id: string;
}
interface IApplicationConfig {
    cultures: ICulture[];
    content: StringMap[];
    loginProviders: string[];
    cities: City[];   when i try to use this
    categories: Category[]; when i try to use this
    posts: IPostModel[]; when i try to use this
}
i already defined models Category, IPostModel in models folder so i don't need to again decalre in typing.d.ts file just want resue by importing.
can you please give me direction 
Thanks

**Comment by asadsahi** [comment]
@sajidali2444 you don't need to declare typings again in typings.d.ts if you have model files in their respective feature folder.

Usually I tend to create intellisense type of models (i.e interfaces) in typings.d.ts and they are available in the whole project so that I don't have to import anything in feature folders just for intellisense purpose.

if you have created:
import { Category, IPostModel, City } from './app/shared/models/post.model';
then you don't need to defined them again in typings.d.ts.

I didn't fully understand your issue. but typings.d.ts already has some examples.

**Comment by asadsahi** [comment]
closing for now. Awaiting response.
