### ISSUE TITLE
dotnet dev-certs

### ISSUE THREAD

**Issue by CodeWorldIndustries** [asadsahi/AspNetCoreSpa#269]
Do I need to install or approve any certs? I'm using Visual Studio Enterprise 2019. I followed your steps but I'm not able to load the SPA.

**Comment by vicentt** [comment]
The problem is that the configured app ports 5005 5007 was NOT in the range :44300-:44398.
There are multiple posible solutions . In my opinion the easiest way to workarround the issue withaout talk about certs and ISS Express is:

For Web Project:

`C:\Program Files (x86)\IIS Express\IisExpressAdminCmd.exe setupsslUrl -url:https://localhost:5005/ -UseSelfSigned`

For STS

`C:\Program Files (x86)\IIS Express\IisExpressAdminCmd.exe setupsslUrl -url:https://localhost:5007/ -UseSelfSigned  
`

Reference: 
https://blog.codeinside.eu/2018/10/31/fix-ERR_CONNECTION_RESET-and-ERR_CERT_AUTHORITY_INVALID-with-iisexpress-and-ssl/

Good Luck!!

**Comment by asadsahi** [comment]
@CodeWorldIndustries 
dev certs are prompted on any initial load of any dotnet web apps and should be good enough, if try this command to add it.

`
dotnet dev-certs https --trust
`
