### ISSUE TITLE
Right align not showing correctly on Menu items

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#36]
Since this update was published the register, login & logout menu items (pull-md-right) sits on the left hand side of the page.  This can also be seen on your live version.  What has changed?

**Comment by asadsahi** [comment]
@kiwiingenuity not sure if this is because of any code change or an environment related issue. When you run the website in dev, it looks ok, Only when you deploy the site to production or run locally in production mode (that includes minified version of packages) the right hand menu moves to the left.

Nothing obvious wrong at the moment, but will investigate this.

**Comment by kiwiingenuity** [comment]
I do not have the same experience as yourself.  When I'm running in dev mode the menu is still not aligning correctly.

**Comment by asadsahi** [comment]
Oh yeah, you were right. Just fixed it and pushed the change, see the change in header.component.html. I think it was a change in newer version of bootstrap which broke the layout.

**Comment by kiwiingenuity** [comment]
Thanks that resolved the reported issue!
However the extra <nav> tag at the top of the page is confusing and the mobile menu does not appear to be working correctly?

**Comment by asadsahi** [comment]
ouch... forgot to save the file after few checks I guess. Pushed the change now.

I will have a look at the mobile menu. Would you mind raising another one please?

Thanks.
