### ISSUE TITLE
Menu options not working on live demo

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#38]
When you click on the login and register menu items, the application does not respond.

**Comment by asadsahi** [comment]
I suspect this is because of the outdated build. My free VSTS build minutes are finished because of frequent CI happening with each checkin. It will be renewed on 1st december and deply the fresh build.

I have tested it locally by building and publishing the production version and its works fine. So we'll see after the new build is deployed on azure.

**Comment by asadsahi** [comment]
Should be working now.

**Comment by kiwiingenuity** [comment]
Agreed!
