### ISSUE TITLE
Typescript Issue??

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#42]
If you open api-gateway.service.ts and look at line 102
I get the error "Supplied parameters do not match any signature of call target"

I suspect this issue only came to light after the last commit?

**Comment by asadsahi** [comment]
@kiwiingenuity can you try with latest code now? I am not getting any error at line 102. But there was an issue with api.gateway service lacking import of Observable as you can see in change history.

**Comment by kiwiingenuity** [comment]
I've included you the new import.
The error is still there.
I should mention that this error is only appearing in Visual Studio.
If you are not getting the same, I suspect we have different versions of typescript?

Now that you have blown away AspNetCoreSpa.xproj I'm a bit bewildered?

**Comment by asadsahi** [comment]
@kiwiingenuity using latest version of typescript and it is part of the project. It could be Visual studio's support for typescript as you said.

xproj was causing issue when deploying to azure. It only successfully deployed if there is only project.json file (not sure why but that issue was only happening recently).

Bear in mind that there are some new project structure changes since 1.1.1 .net, which I will be making at some point. I only use VS code and that doesn't support csproj yet, which is new project file for .net projects. I am sure Visual studio 2015 still support project.json based projects which don't have any xproj or solution files. Have you tried those?

**Comment by asadsahi** [comment]
@kiwiingenuity this is added back in again. Can you check if you are still having this issue?

**Comment by asadsahi** [comment]
Closing for now, if issue exist please let me know.
