### ISSUE TITLE
How to setup angular-Material change for bootstrap?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#44]
Thank so much

**Comment by badre429** [comment]
any description why not ***@angular/material***

**Comment by kanpinar** [comment]
:) in turkish we say "içinde içinde"
That means Solution is in it....
There is a few questions about that, you can check...

For your need steps may be (I did with this way)
  1- read 
[https://github.com/angular/material2/blob/master/guides/getting-started.md](         https://github.com/angular/material2/blob/master/guides/getting-started.md)

  2- Start with small target, so skip themes ext.
  3- Be carefull about 
         webpack configurations    
         Client\styles vendor.css    / You need to add here Material Icons and Roboto Fonts
         .angular-cli.json               / in docs they say styles and scripts section to use but not effective for thi s project 
       
And last my app.component.ts looks like this. I am not sure best but working
@Component({
    selector: 'appc-root',
    templateUrl: './app.component.html',
    styleUrls: [
        './app.component.scss'
        ,'./primengtheme.scss'
        ,'./primengbase.scss'
    ],
    encapsulation: ViewEncapsulation.None
})

**Comment by ehouarn-perret** [comment]
@kanpinar have you experienced some discrepancies with the original MS SPA Angular template for ASP.NET Core 2.0(https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Microsoft.DotNet.Web.Spa.ProjectTemplates/angular)?

Long story short, I have a "working" solution supporting Angular Material 2 (no JS warning when running and the controls are all running fine). However, I am facing one single issue that bothers me a bit when webpack is doing its job file changes, seems the rendering is duplicated on the go, if I reload the page, it's fine but I loose the i-don't-need-to-refresh-my-page-to-see-observe-changes feature: https://github.com/aspnet/JavaScriptServices/issues/1231
I am wondering if it's due to the fact that I had to change the tag for the server pre-rendering `asp-prerender-module`: https://github.com/aspnet/JavaScriptServices/blob/04fe1204a95ee09c9c0bf14c81e680c6f38f37dc/templates/Microsoft.DotNet.Web.Spa.ProjectTemplates/angular/Views/Home/Index.cshtml#L5


Which on my side has had to be replaced by `asp-ng2-prerender-module` in order to support Angular Material 2:
https://github.com/ehouarn-perret/EhouarnPerret.CSharp.AngularMaterial2/blob/92151f65e683b3a193b4d4985428ad244dae0ae8/EhouarnPerret.CSharp.AngularMaterial2/Views/Home/Index.cshtml#L5

**Comment by atrevers** [comment]
@ehouarn-perret Have you managed to find a solution to this issue? I'm getting exactly the same issues with HMR (like you, I've had to change the tag for server pre-rendering).
