### ISSUE TITLE
ie9&10&11 support

### ISSUE THREAD

**Issue by najimtab** [asadsahi/AspNetCoreSpa#54]
I noticed that your demo don't work on IE. Could you tell me why? 
Isn't it related to ES6 support?

thx

**Comment by asadsahi** [comment]
@najimtab will look into this.

**Comment by asadsahi** [comment]
@najimtab This should be fixed now. The problem was some polyfills missing which IE requires:

these were commented out:

import 'core-js/es6';
// Added parts of es6 which are necessary for your project or your browser support requirements.
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/weak-map';
import 'core-js/es6/weak-set';
import 'core-js/es6/typed';
import 'core-js/es6/reflect';
// see issue https://github.com/AngularClass/angular2-webpack-starter/issues/709
import 'core-js/es6/promise';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

I have also added some explanation that IE9 and below will not be supported because of Bootstrap 4 restriction.

**Comment by najimtab** [comment]
It works perfectly. Hanks  @asadsahi
