### ISSUE TITLE
Example site not working 100%

### ISSUE THREAD

**Issue by mika76** [asadsahi/AspNetCoreSpa#58]
- Register button never becomes enabled and no validation messages are shown
- Trying to log in with any of the external services throws a http 500 error
- Animation example also does not do anything for go

**Comment by asadsahi** [comment]
@mika76 can you provide details of your environment?

Browser version, OS etc?

Thanks

**Comment by mika76** [comment]
Sure, sorry should have done that originally. 

Chrome 56.0.2924.87 (64-bit), MacOS Sierra 10.12.3

I  just tried it again. 
- There were validations this time on the register form (maybe some script didn't load the first time?) but clicking the button only causes the below error:
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Trying to log in with google gives me:
> Uncaught Error: uBlock Origin: aborting content scripts for http://aspnetcorespa.azurewebsites.net/api/account/ExternalLogin?provider=Google
    at contentscript.js:90
- Animations - the stop and go do nothing really only toggle. Toggle twice and the box disappears.

**Comment by mika76** [comment]
Also polyfills.js gives a 404

**Comment by asadsahi** [comment]
@mika76 you will not be able to use oauth logins on live site because of reason exaplained [here](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup):

You can follow [this ](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup)wiki to implement in your project.

Animations are working fine on chrome, can't thing of any environment specific issue with animations as they are supported in chrome out of the box.

When I say polyfills for animations I am not referring to the polyfills that this project is using, but the [polyfills ](https://github.com/web-animations/web-animations-js)library which is required to support javascript animations.

Closing this for now, but If you encounter any issues after following wiki to implement oauth, I can reopen it.

**Comment by mika76** [comment]
There's not much point in having an example site up if you're going to disregard all the problems seen on it, all it does is make me distrust the code. Why would I download and use my time to try something where it's own example does not work?

PS: I got all these problems on chrome...

**Comment by asadsahi** [comment]
@mika76 have you managed to get social account login working by following the wiki link i mentioned above?

Regarding animations can you see animations between home and example pages? Can you see any errors in console when the application loads?

Unfortunately I am not using OSx, but I can look further if you can provide any errors from console if you are receiving.
