### ISSUE TITLE
why not angular-cli 

### ISSUE THREAD

**Issue by badre429** [asadsahi/AspNetCoreSpa#70]
most of angular project on github use angular-cli can you explain why  you are not using it in this project

**Comment by asadsahi** [comment]
@badre429 let me explain as much as I can to clarify.

The approach by angular-cli vs this project which is based on asp.net core spa/javascript services (details [here](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/)) is different. Angular cli manages client side build + code scaffolding + few other things which are specific to client aretefact like typescript/html/css/scss files. However, you still need a server-side(e.g node, .net) or server-less (e.g firebase) backends to make an angular-cli project to communicate. For server-less architecture you can rely purely on angular-cli. Also, there is a [proxy mechanism](https://github.com/angular/angular-cli/wiki/stories-proxy) in angular-cli project which you can leverage to point your backend calls to another web address e.g a node based backend running seperately in another command line process locally.

This is an Asp.net core single page full stack project and the whole purpose of using some of the new tools (e.g [Asp.Net core javascript services](https://github.com/aspnet/JavaScriptServices)) is so that we don't have to manage client/server side build tools and processes seperately. With just a single click or F5 key (Visual studio debugging shortcut key) you are running a project which is single page angular application with .net backend. A huge shout out to @SteveSandersonMS from microsoft who has built this framework to make developer's life easy. Internally .net is managing the client build tools, which angular-cli manages using the same module bundle called webpack. So that is common tool between cli and this project.

Having said that, this project still uses angular-cli but only for code scaffolding for now becuase why not. You can find more information on readme of this project for usage of code scaffolding in this project. In future I am planning to leverage more tools from cli which are angular specifc e.g AOT/SSR etc.

Hope that explains the reason why this project cannot solely rely on angular-cli.
