### ISSUE TITLE
What is the purpose of vendor configuration in webpack.dev.js

### ISSUE THREAD

**Issue by skorunka** [asadsahi/AspNetCoreSpa#89]
What is the purpose of vendor configuration in webpack.dev.js?

Do I have to add there the packages I want to use?

Thank you.

**Comment by asadsahi** [comment]
@skorunka yes, you would like to add any 3rd party packages as this list gets added into webpack dll bundle. Webpack dll bundle increases the speed of rebuilding applciation in dev by by passing these 3rd party packages reading from that section since these packages don't change, so we don't need to include them in webpack rebuild process.

**Comment by skorunka** [comment]
Lovely! ta
