### ISSUE TITLE
vendor.css -> "Uncaught Error: Expected 'styles' to be an array of strings."

### ISSUE THREAD

**Issue by skorunka** [asadsahi/AspNetCoreSpa#92]
Having `vendor.css` empty or :
```
@import '../../node_modules/font-awesome/css/font-awesome.css';
```
Resulting in the browser error: 'Uncaught Error: Expected 'styles' to be an array of strings.'.

Any idea what might be wrong? ta.

**Comment by skorunka** [comment]
This is actually problem related to while trying to add external CSS files using `styleUrls` in `@Component`....

**Comment by skorunka** [comment]
When the file is added as cscc all works. Why adding CSS files does not work?

**Comment by asadsahi** [comment]
@skorunka this project uses component css to be SCSS instead of css. CSS is a valid SCSS, so you can use CSS as normal in SCSS files. All the component are styled inline with JS bundles.

Vendor files are css and they are extracted as seperate css bundle. If you like components to use css you might need something like this:
https://github.com/AngularClass/angular-starter/blob/master/config/webpack.common.js#L155

**Comment by skorunka** [comment]
@asadsahi Ok, no worries. I prefer SCSS over CSS. Maybe put this in to readme to avoid confusion.

**Comment by asadsahi** [comment]
Thanks @skorunka now you know that, how about creating a wiki for this?

Would you like to create one explaining this? :)

**Comment by skorunka** [comment]
@asadsahi Will try ;)
